FROM mysql/mysql-server:latest

# setup mysql, allow remote access and create user
RUN sed -i -e"s/^bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/" /etc/my.cnf

ADD create_database.sql /docker-entrypoint-initdb.d/
ADD create_user.sql /docker-entrypoint-initdb.d/
